# Generated by Django 5.0 on 2023-12-16 06:11

import django.core.validators
import my_plant_app2.web.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(2)])),
                ('first_name', models.CharField(max_length=20, validators=[my_plant_app2.web.validators.validate_firs_letter])),
                ('last_name', models.CharField(max_length=20, validators=[my_plant_app2.web.validators.validate_firs_letter])),
                ('picture', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
