# Generated by Django 5.0 on 2023-12-16 06:42

import django.core.validators
import my_plant_app2.web.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Outdoor', 'Outdoor Plants'), ('Indoor', 'Indoor Plants')], max_length=14)),
                ('name', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(2), my_plant_app2.web.validators.validate_only_letter])),
                ('image', models.URLField()),
                ('description', models.TextField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
